title: inki
description: Wireless information displays for modern spaces
theme: jekyll-theme-minimal
show_downloads: false
logo: /assets/images/inki_octopus.png
github:
  is_project_page: true
  repository_url: https://github.com/c0de111/inki

